### ISSUE TITLE
Implement PinchDistance instead of PinchStrength in pinch gesture

### ISSUE THREAD

**Issue by LabeVR** [SDraw/driver_leap#10]
As of the current release, the pinch gesture is implemented using the [Leap::Hand::PinchStrength](https://docs.ultraleap.com/api-reference/unity-api/class/class_leap_1_1_hand.html?highlight=pinch#var-Leap.Hand.PinchStrength) variable however this gesture calcuates the pinch gesture based on all fingers, its probably prefered to use [Leap::Hand::PinchDistance](https://docs.ultraleap.com/api-reference/unity-api/class/class_leap_1_1_hand.html?highlight=pinch#var-Leap.Hand.PinchDistance) which returns the same values but filters only the thumb and index finger to be calculated, which is more preferable and harder to misclick.

Docs for both of these are embed on the words itself and can also be found [here](https://docs.ultraleap.com/api-reference/unity-api/class/class_leap_1_1_hand.html)

**Comment by SDraw** [comment]
Reasonable, on it

**Comment by LabeVR** [comment]
tysm!

**Comment by SDraw** [comment]
Implemented in release [1.4-232](https://github.com/SDraw/driver_leap/releases/tag/1.4-232).
