### ISSUE TITLE
Smooth hand rotation and position while system dashboard is shown

### ISSUE THREAD

**Issue by LabeVR** [SDraw/driver_leap#11]
Another big problem with hand tracking interaction is **precision**, sadly, i've experimented with it a bit and both gestures (Pinch and Finger bend) cause a drift that is responsible for the laser to be shaky/not precise.

This renders interactions with the steam overlay very hard and interactions with the desktop almost impossible.

A possible fix for this would be to check if a system overlay is open and if so, switch the position of the controller to use [Leap::Hand::StabilizedPalmPosition](https://docs.ultraleap.com/api-reference/unity-api/class/class_leap_1_1_hand.html?highlight=pinch#var-Leap.Hand.StabilizedPalmPosition), However for rotation the lerp function in the glm library could be used.

I had a problem with implementing the check for if a system overlay is open cause i couldnt include OpenVR to actually make this check, you could try to include it but im not sure if it works, lmk. (I've tested the smoothing with a toggle controlled by the system buttton, however this really dosent work as it gets desynced really fast)

**Comment by SDraw** [comment]
`stabilizedPalmPosition` was unreliable for me in past, so I don't want to touch it anymore.
But smoothing rotation of controllers when SteamVR dashboard is open, sure thing, on it.

**Comment by LabeVR** [comment]
Nice, is it possible to lerp the vector3 that handles the position of the controllers too?

**Comment by SDraw** [comment]
Of course.
Implemented in release [1.4-232](https://github.com/SDraw/driver_leap/releases/tag/1.4-232).
