### ISSUE TITLE
In VRchat profile hand doesn't goes to reset position 

### ISSUE THREAD

**Issue by 203Null** [SDraw/driver_leap#12]
Not like regular mode, hand stay hover in the air and steamvr still shows controller connected (Soild icon instead pulsing). This made controller unusable. Not sure is this intended or not.

**Comment by SDraw** [comment]
Yes, [it's intended](../blob/master/driver_leap/CLeapHandController.cpp#L513).
VRChat changes controls if pose for one controller is received as not valid, making gestures not to work and triggering broken movement. This behaviour started to occur when VRChat was updated to newer version of Unity.

**Comment by 203Null** [comment]
Thank you for clarify
