### ISSUE TITLE
Mismatch names

### ISSUE THREAD

**Issue by kariyann** [SDraw/driver_leap#13]
Hello,
it's not really an issue, but as I was trying to deactivate some controls, it appeared that control's names in the "control_config.xml" were false.
Indeed, for the controls I mapped :
    "grip" is not grip but trigger
    "touchpad" is not touchpad but grip
    "buttonB" is not buttonB but buttonA
    "thumbstick" is not button thumbstick but buttonB

**Comment by SDraw** [comment]
Alright, I'll take a look

**Comment by SDraw** [comment]
You're right. There was a missing comma. Should be fixed after building 4ebe38e6.

**Comment by kariyann** [comment]
Seems to be ok now. Thanks
