### ISSUE TITLE
Will this work with Hyperion?

### ISSUE THREAD

**Issue by vpotapenko** [SDraw/driver_leap#13]
hello, are you going to support Hyperion? thanks

**Comment by SDraw** [comment]
Probably no, because I don't have specific hardware to test it out.

**Comment by vpotapenko** [comment]
but I guess the hardware is the same, it is just a new software version?

**Comment by SDraw** [comment]
Afaik, it's entirely different software with specific hardware requirements:
<kbd>![2024-07-07_13-09-13](https://github.com/SDraw/driver_leap/assets/4295751/ccc02291-71d5-4a53-91a0-d5115a48eadc)</kbd>
Since I have only first Leap Motion, I can't use it for driver integration.

**Comment by vpotapenko** [comment]
ok I see, thank you
