### ISSUE TITLE
Toggle the spawn of emulated controllers

### ISSUE THREAD

**Issue by SupertoineFR** [SDraw/driver_leap#14]
As per title, a good feature is the ability to toggle the status of the emulated index controllers, allowing you to switch between leap motion and real controllers without the need to restart steamvr.

This would be done by simulating the virtual controllers disconnecting, and if you have other controllers connected to steamvr, steamvr will switch hands between virtual and physical automatically.

**Comment by Alphie-U** [comment]
I second this. I've found this being a problem for my use-case.

**Comment by ThatGuyThimo** [comment]
I third this. This is also a problem i have run into and would like not to have to remove the driver every time i want to use my normal controllers.

**Comment by SDraw** [comment]
Implemented in f2c3050c6339e86c375cc8083a587561de4245ce, released in [1.4-233](https://github.com/SDraw/driver_leap/releases/tag/1.4-233).

**Comment by SDraw** [comment]
Implemented in f2c3050c6339e86c375cc8083a587561de4245ce, released in [1.4-233](https://github.com/SDraw/driver_leap/releases/tag/1.4-233).

**Comment by SupertoineFR** [comment]
![images](https://github.com/user-attachments/assets/af01a92e-ed4c-45b9-8b3c-7a59f42674c2)
