### ISSUE TITLE
Using controllers or vive trackers for out of boundaries position?

### ISSUE THREAD

**Issue by Charmandrigo** [SDraw/driver_leap#15]
Could be possible to use steamvr controllers as a way to keep tracking your hands when the leap camera isn't seeing them?

think about either vive trackers or wands tied to your forearm + a hand to controller offset in CM set in the driver, so arm movement is still present when the cameras can't see your hands, it could be useful!

**Comment by SDraw** [comment]
Problem of this approach is that attached trackers/controllers to your forearm would have fixed local transformation, meanwhile emulated controllers are constantly moving in local space (if parent is forearm).
For example, [MANUS VR Gloves](https://www.manus-meta.com/vr-gloves) have trackers attached over opisthenar, but in our case those will interfere with Leap Motion controller for detecting hands properly.
Suggestion itself is nice, but current implemetation of hand pose translating to controller pose is preventing to implement this idea.
