### ISSUE TITLE
Hand rotation is off and tracking is very scattered

### ISSUE THREAD

**Issue by AIREYVR** [SDraw/driver_leap#16]
i seem to be having a problem where my hands are rotated inward too much on my coulus .

**Comment by AIREYVR** [comment]
Tracking was an issue on my end but hand rotations on index emulation isnt proper

**Comment by SDraw** [comment]
Hm, could you provide some screenshots on this issue?
From mathematical point of view position and rotation of controllers are calculated right, so it's possible that rendermodels definitions in JSON files (valve_controller_knu_1_0_left/right.json) for controllers are made with offsets.

**Comment by asktoby** [comment]
I'm having this issue on Index also.
I've done a video to demonstrate it:
https://www.youtube.com/watch?v=oG_kHEl1vAo&feature=youtu.be

**Comment by asktoby** [comment]
I believe this should no longer be marked "waiting response" but I do not have permission to remove the label

**Comment by SDraw** [comment]
I still think that it's models offset causing this missalignment.

**Comment by Maxuos** [comment]
SDraw, first of all thank you for all of your efforts... great stuff man!
Been testing on my Leap as well in SteamVR+VRChat, mounted on HMD. 
Everything is smooth.. the only issue I am facing is my hands are not aligned properly.
In leap visualizer hands are aligned properly, in VRChat my hands angles are off, any ideas how to sort it out?

**Comment by allybam** [comment]
Same issue as Maxuos, my hands are also off angle. What is the correct X Y Z position?

**Comment by havok2-htwo** [comment]
Hello,
is the project still in progress? It looks to me as if one line of code has been forgotten just before the finish line. Unfortunately, I have not yet received the project in compliance. I'm not a full-time programmer, but shouldn't it be enough to set a rotation offset to X,Y,Z before the handover? Everything works fine, but the hands are just 45° outwards and up I think. Also the hands are about 20cm apart, even if I press my real index fingers together. In the Config there are already offset values, but they don't hurt. Couldn't you solve this in the same way with a Config? 

Left Hand - Offset Rotation x,y,z
Left Hand - Offset Position x,y,z
Right Hand - Offset Rotation x,y,z
Right Hand - Offset Position x,y,z

Thanks!

**Comment by SDraw** [comment]
Refer to #38.

**Comment by asktoby** [comment]
I just tested again using the latest release driver_leap_1.0-174 and the issue is still there.
Am I supposed to manually enter the offsets in the config?
