### ISSUE TITLE
How to disable?

### ISSUE THREAD

**Issue by asktoby** [SDraw/driver_leap#19]
I have this installed now, but I don't always want to use it.
How do I temporarily disable it (akin to "turning off the controller") when I want to use normal controllers?

**Comment by SDraw** [comment]
Latest commit has this functionality. Set value attribute for param 'enabled' to 'false' in control_config.xml.

**Comment by asktoby** [comment]
Am I right that to use the latest commit do I would need to build it in Visual Studio 2013?

**Comment by asktoby** [comment]
I've figured out I can disable the latest released version by renaming
C:\Program Files\SteamVR Leap Motion driver\leap
to
C:\Program Files\SteamVR Leap Motion driver\was leap
and restarting SteamVR
