### ISSUE TITLE
Leap Motion + SteamVR -> OpenVR Shutdown immediately after application run

### ISSUE THREAD

**Issue by FlorianMathis** [SDraw/driver_leap#21]
Hi all,

I'm facing an error and could not figure out the source of the problem. The combination of both (the leap motion and a htc vive controller (or vive tracker)) causes an automatically "OpenVR Shutdown". Anyone faced this problem and has a solution/workaround?

Best regards,
flo

**Comment by SDraw** [comment]
I've updated driver to latest OpenVR SDK, there are few changes that are connected with applications.
Try to use auto-builded release 157.
If nothing helps, post 'vrserver.txt' file from <Steam>/logs folder here.

**Comment by FlorianMathis** [comment]
Thank you @SDraw  - will take a look soon!

**Comment by FlorianMathis** [comment]
@SDraw don't know what exactly this error caused but it works now, thanks!
