### ISSUE TITLE
I'm using an HP Leap Motion Keyboard. How do I control it? I turn on steamVR after my hand is the opposite

### ISSUE THREAD

**Issue by Mosssssssssssssssssssssssssssssssssssss** [SDraw/driver_leap#23]
I can't find the right direction

**Comment by 203Null** [comment]
Tape the keyboard to your HMD

**Comment by Mosssssssssssssssssssssssssssssssssssss** [comment]
> Tape the keyboard to your HMD

lol,I tried the same direction, but the hand was the opposite

**Comment by SDraw** [comment]
An interesting situation, I'll try to come up with something.

**Comment by SDraw** [comment]
Seems like I can't solve this one, sorry.
