### ISSUE TITLE
move does not work

### ISSUE THREAD

**Issue by Moony4012** [SDraw/driver_leap#26]
Hello, when pressing Arrow keys or Num2,8,4,6 it does not rotate, move me
"Thumbstick direction - arrow keys for left hand, Num2/8/4/6 keys for right hand; available when NumLock is active"

**Comment by SDraw** [comment]
Try latest release, perhaps it will help.

**Comment by Moony4012** [comment]
still not move with using Num Active "driver_leap_1.0-174_x64"

**Comment by ShootingKing-AM** [comment]
You should have the corresponding hand tracked by Leap controller then simultaneously press Numpad keys or Arrow keys. Also in which game profile are you in @Moony4012 ?
