### ISSUE TITLE
Can't seem to install for some reason, troubleshooting instructions do nothing

### ISSUE THREAD

**Issue by InsaneGrox** [SDraw/driver_leap#27]
So I've been trying to get this driver installed, but it doesn't get detected by steamVR, however I did read the troubleshooting stuff, and for some reason, vrpathreg commands are just asking how I want to open a file, and don't do anything else, I can't open command prompt in folders so I'm forced to use powershell.
![ps](https://user-images.githubusercontent.com/54233743/71319145-5c2eef80-2468-11ea-978f-4f93d032ee7c.png)

**Comment by SDraw** [comment]
You don't need to run vrpathreg if you're extracting to 'drivers' folder of SteamVR, only additional line in 'steamvr.vrsettings' is required.

**Comment by InsaneGrox** [comment]
I tried that, but the driver doesn't load despite being in the drivers folder, I have orion drivers running and my device turned on, but no hands or controllers appear.

**Comment by SDraw** [comment]
Hm, could you send vrserver.txt from 'Steam/logs'?

**Comment by InsaneGrox** [comment]
oh my fucking god, my steamVR was in safe mode...
