### ISSUE TITLE
Beat Saber FlatHandPalmTowards

### ISSUE THREAD

**Issue by Lucas24865** [SDraw/driver_leap#28]
Hi, i have an issue with beat saber and the gesture FlatHandPalmTowards. Sometimes when i hit the note i accidentally make this gesture and it open the menu. I dissable all the controls i can but i cannot dissable that. Below i attach my control_config but in txt format
[control_config.txt](https://github.com/SDraw/driver_leap/files/3995544/control_config.txt)

**Comment by SDraw** [comment]
Try latest release, perhaps it will help.

**Comment by Lucas24865** [comment]
I solved that changing the pause option in game from instant to hold. Thanks for reply and sorry for not close the issue before
