### ISSUE TITLE
Alternative placement of the leap motion sensor on a fixed position in front of the person possible?

### ISSUE THREAD

**Issue by pcky** [SDraw/driver_leap#3]
Hi,
This is kind of a feature request. Does it make sense to implement an alternative configuration where we can use the sensor placed on a fixed position like a desk or monitor? This way we could keep a setup including a Oculus Go or GearVR completely untethered, although this means a limited range of hand detection in front of the HMD. Thanks!

**Comment by SDraw** [comment]
Hm, I can try to do that.

**Comment by stanier** [comment]
@SDraw, anything we can do to help with this?  I'm not too familiar with OpenVR but it sounds like this might be do-able by flipping the axes, change a couple offsets and maybe change the zero positions.  Would probably be better to do as a separate branch then merge in once it can be togged in control_config or something similar

**Comment by SDraw** [comment]
@stanier Perhaps 😃 
Implemented in 9ca271d1.
