### ISSUE TITLE
Multi controller control

### ISSUE THREAD

**Issue by crazyzack53** [SDraw/driver_leap#31]
I've been using this driver recently, and it is amazing. However, just recently I realized that I could have both my rift s controllers and the leap motion driver at the same time, however games will only take input from one controller untill I deactivate it. So I was wondering if it would be possible to make a sort of hybrid controller by taking inputs from both. This would really help with things like walking/ teleporting (since there isn't a great way now) and easier navigation.

**Comment by SDraw** [comment]
You can, but it's fully up to you. I don't have any device for implementing and testing this.
