### ISSUE TITLE
Leap hands teleport to the ground when out of view.

### ISSUE THREAD

**Issue by officialnochill** [SDraw/driver_leap#35]
They should instead be stuck at the last known postion, this bug makes Half-Life: Alyx unplayable as you cannot put resisn as well as ammo in your backpack. 

Unrelated suggestion: Allow us to bind leapmotion gestures to keyboard buttons (like the thumbstick in index mode). This would be AMAZING as you could use a leapmotion for finger and hand tracking with a controller in your hand for the buttons.

**Comment by SDraw** [comment]
Added setting 'handsReset' in b1a949aa. By default it's set to **false** to prevent this behavior.
