### ISSUE TITLE
How to switch from vive controller to index contoller?

### ISSUE THREAD

**Issue by MJ26gaming** [SDraw/driver_leap#36]
Where is the setting for this?

**Comment by crazyzack53** [comment]
You have to go to the settings For leap 
(I think it's called control config) and then you change the value from vive to index

**Comment by nikaji** [comment]
I believe you're looking for the "emulated_controller" setting defined in `SteamVR/drivers/leap/resources/settings.xml`.

You'll want to change the value from `vive` to `index`:
`<setting name="emulated_controller" value="index"/>`
