### ISSUE TITLE
Null driver setting not working

### ISSUE THREAD

**Issue by chenj209** [SDraw/driver_leap#37]
I tried to use this driver_leap with null driver setting since I don't have a VR headset right now. However, SteamVR does not recognize the controller for some reason.

Here is the steps to reproduce:
On windows computer, I have leap motion orion 4.0.0+52173 version installed
1. add "activateMultipleDrivers" : true, "forcedDriver": "null", to near the top of the "steamvr" section of your steamvr.vrsettings config file.
2. set driver null to be enabled in \SteamVR\drivers\null\resources\settings\default.vrsettings
3. Create 'leap' folder in '<SteamVR_folder>/drivers'
4. Grab latest release archive
5. Extract archive to '<SteamVR_folder>/drivers/leap'
6, Add line in section 'steamvr' of '<Steam_folder>/config/steamvr.vrsettings' file: "activateMultipleDrivers": true,
7. Open console as administrator in '<SteamVR_folder>/bin/win32' (or '<SteamVR_folder>/bin/win64') and execute command:  vrpathreg adddriver "path_to_leap_folder"

The result is no controller is recognized

**Comment by chenj209** [comment]
![steamVRleapmotionbug](https://user-images.githubusercontent.com/23141871/82455921-8faa9000-9a81-11ea-9dd8-f9dc94289724.png)

**Comment by SDraw** [comment]
Seems like you've mixed first and second methods of installation. With first method you don't need to add path to driver with **vrpathreg**. Try to remove added path in **vrpathreg** and check if SteamVR isn't running in safe mode.
