### ISSUE TITLE
Disable a single hand option

### ISSUE THREAD

**Issue by pkaser** [SDraw/driver_leap#4]
So I use this in VR in Aerofly FS2, and they have things hard mapped to the left controller (gestures & buttons). It would be nice if it ignored the left (or right) hand altogether, because it is always on the yoke and if it's in view it interferes. Maybe enable or disable in a config file.

**Comment by SDraw** [comment]
Sounds reasonable. I'm on it.

**Comment by SDraw** [comment]
Added in 939e6cd.

New config parameters:
```XML
<param name="rightEnabled" value="true"/>
<param name="leftEnabled" value="true"/>
```

**Comment by pkaser** [comment]
Awesome! Thanks!
