### ISSUE TITLE
Are you able to get it working with vs 2019?

### ISSUE THREAD

**Issue by Rorybabory** [SDraw/driver_leap#40]
the title

**Comment by ShootingKing-AM** [comment]
Maybe you can say whats the problem exactly ? or vs2019 logs ?

**Comment by SDraw** [comment]
Project is made for Visual Studio 2013 with C++11 standart because there is no need in new features of C++14, C++17 or C++20. If you wish to update project I suggest you to fork this repository, make changes and maintain it.
