### ISSUE TITLE
Instructions dont lead to a working install

### ISSUE THREAD

**Issue by pkaser** [SDraw/driver_leap#41]
I have followed your vague instructions the best I could and it doesnt work.  Can you please take some time and fix the instructions.  I have attempted this install 4 times in the last 3 years and I have never gotten it to work

**Comment by ShootingKing-AM** [comment]
I have tried to elaborate the instructions and general Readme.md in PR#45. You can try to read that if it helps, alternatively you can find the full Readme.md in [ShootingKing-AM:master](https://github.com/ShootingKing-AM/driver_leap)
