### ISSUE TITLE
Any way to turn off gestures while fingers keep moving?

### ISSUE THREAD

**Issue by ionmcains** [SDraw/driver_leap#42]
Hi,

Is there any way to turn off gestures while fingers continuing moving? I'm using Autodesk VRED and Teleport becomes crazy

It's a grest plugin

Thanks a lot

**Comment by mortrem** [comment]
There is a config file in the ressources directory where you can disable some or all hand sign. Now I have to find how to remap them to key

**Comment by SDraw** [comment]
@mortrem Remapping of gestures in performed in source code. You can't do it editing `settings.xml`.
