### ISSUE TITLE
Flick gesture and a pinch-and-twist gesture

### ISSUE THREAD

**Issue by pkaser** [SDraw/driver_leap#5]
Can a flick gesture be created? Like flicking a switch up or down depending on the palm direction.

Pinch and twist, like tuning a radio dial, too

**Comment by SDraw** [comment]
But for what action will it be assigned for controllers?

**Comment by pkaser** [comment]
If I am understanding the question, it would depend. If you pinch and twist to the right, then it would map to a key press that would increase the value, and left would be the key to decrease the value.  Is that what you mean?


________________________________

**Comment by SDraw** [comment]
Currently driver uses all buttons of HTC Vive controller. What button can be assigned with flick gesture if there is no available button for this?
