### ISSUE TITLE
Pinch to trigger/click hand gesture

### ISSUE THREAD

**Issue by Reiko9** [SDraw/driver_leap#5]
The Contact of the index finger with the thumb is becoming an industry standard (especially known for its use on quest headsets) for the trigger operation and should be less prone to accidental clicks unlike an index finger movement exclusively.

Likewise the aggressiveness i have to move my index finger for it to count as a trigger press on the leap-motion 2 i find rather painful after a short while and it contributes to carpal tunnel syndrome.

 What will also be interesting is Vrchat as of last May 2024 has a Developer update that includes SteamVR Skeletal input natively to vrc and it will be interesting if that creates gesture system conflicts with driver_leap, but it may remove the need for Index emulation and support full blown finger spreading.

https://ask.vrchat.com/t/developer-update-2-may-2024/24284
"The first platform to utilize this new cross-platform hand tracking system is SteamVR. The skeletal data is applied any time skeletal data is available, regardless of whether the fidelity level is estimated, partial or full."

I do not know when this will be rolled-out into regular builds, but i believe there is a lot of potential.  Especially if it means one can use their regular controllers and have the hands animated independent of the controllers, so locomotion still works well.

Although a current work-around I have used for locomotion is to connect a usb gamepad and make sure the vrchat window is selected and this basically controls vrc independent of SteamVr to allow at least movement. 

Thanks for your hard work and i have seen what looks like finger-spreading working in SteamVR home with driver_leap, so vrc looks to be the bottleneck at this point.

**Comment by SDraw** [comment]
> The Contact of the index finger with the thumb is becoming an industry standard (especially known for its use on quest headsets) for the trigger operation and should be less prone to accidental clicks unlike an index finger movement exclusively.
> Likewise the aggressiveness i have to move my index finger for it to count as a trigger press on the leap-motion 2 i find rather painful after a short while and it contributes to carpal tunnel syndrome.

I guess adding trigger type modes list with `Finger bend` and `Pinch` options could help. Alright, added to a list.

>What will also be interesting is Vrchat as of last May 2024 has a Developer update that includes SteamVR Skeletal input natively to vrc and it will be interesting if that creates gesture system conflicts with driver_leap, but it may remove the need for Index emulation and support full blown finger spreading.

Skeletal input is linked with device itself, so it's not possible to supply skeletal data without emulating device. Moreover, almost all current VR games are made in a way that only Index controllers have skeletal data, and this is totally wrong on behalf of developers.

> https://ask.vrchat.com/t/developer-update-2-may-2024/24284
"The first platform to utilize this new cross-platform hand tracking system is SteamVR. The skeletal data is applied any time skeletal data is available, regardless of whether the fidelity level is estimated, partial or full."
> I do not know when this will be rolled-out into regular builds, but i believe there is a lot of potential. Especially if it means one can use their regular controllers and have the hands animated independent of the controllers, so locomotion still works well.

Would you look at that, they have finally started to do something, even though NeosVR, Resonite and ChilloutVR had it a while ago. Yet VRChat devs are still ignoring community request for integrating Leap Motion for 7 years.

**Comment by SDraw** [comment]
Implemented in [1.4-231](https://github.com/SDraw/driver_leap/releases/tag/1.4-231) (10ca3aecd5c2cf4be714acdecf24f6f1e03c6735). Still relies on how good Leap Motion itself can detect pinch gesture itself.
