### ISSUE TITLE
Hand Control

### ISSUE THREAD

**Issue by itguy327** [SDraw/driver_leap#7]
I'm using a Leap Motion 1 and having difficulty navigating the Steam VR Home/Dashboard. My Vive wands are kinda caput and this would be great for basic navigation but I'm not sure if I understand the usage completely.

Sorry for adding another issue, but I thought it appropriate for it to be separate from my Steam Controller/XBOX Controller questions.

Thank you again for your work

**Comment by SDraw** [comment]
Since most input in those apps requires usage of trigger button, it's tied how good Leap Motion can detect your index finger bending or pinch gesture (depends on `Input - Trigger mode` setting).
On practice, it works better when Leap Motion actually sees your index/(and thumb) finger(s) unobscured.

**Comment by itguy327** [comment]
Perhaps I did not keep my hands visible. I will keep trying. Thank you
again for your work.
