### ISSUE TITLE
Will this app work with Somnium VR1 hands tracking (based on Ultraleap cameras)

### ISSUE THREAD

**Issue by vpotapenko** [SDraw/driver_leap#8]
Hello,
Could you please comment/confirm if this app will work with Somnium VR1 headset? It uses Ultraleap cameras for hands tracking. Thank you

**Comment by LabeVR** [comment]
If it uses the ultraleap services then it will work with this driver

**Comment by SDraw** [comment]
> If it uses the ultraleap services then it will work with this driver

Should be like this, probably
