### ISSUE TITLE
Thumbstick Direction with Index Mode

### ISSUE THREAD

**Issue by kool601** [SDraw/driver_leap#9]
Maybe have it like the touchpad circle gesture, except instead of using your index you use your thumb?

EDIT: Also, my tracking is extremely jumpy and glitchy Leap Motion-wise. I can't figure out why, but that might be something else. I have it plugged directly into the Vive, maybe that's the issue? In that case, I dunno where to plug it in then. XP

**Comment by lazzonn76** [comment]
Now it works fine for me, I managed to understand the files to copy and the gestures work, I just have to change the controllers I want to put those of the index in place of others, your leap can connect it to a USB 3.0 port direct without a hub to improve performance

**Comment by SDraw** [comment]
I don't think that it will be good solution because thumb is directed to opposite hand palm very often.

**Comment by kool601** [comment]
Ah, yeah that makes sense. I hope someone can come up with a good gesture for thumbstick direction. ^w^

**Comment by SDraw** [comment]
I will add new configuration line in control_config.xml to enable thumbstick direction from keyboard with arrow and numpad keys.

**Comment by SDraw** [comment]
Implemented in d48b3c97, release will be updated after auto-build.
If NumLock is active, use arrow keys for left hand controller, Num2/8/4/6 for right hand controller.

**Comment by SDraw** [comment]
Implemented in e52397d1.
Thumbstick direction is set for left hand controller with arrow keys and numpad keys (Num2/8/4/6) for right controller as long as NumLock is active.

**Comment by lazzonn76** [comment]
Thank tou very much Sdraw🙏
